# -*- coding: utf-8 -*-
"""major_pro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-_xaFi423EhbfcehmDPTjZbb8yOkRAw
"""

import pandas as pd
import numpy as np
import re
import json
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()
def safe_read_json(path):
    data = []
    with open(path, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            try:
                data.append(json.loads(line))
            except json.JSONDecodeError:
                print(f"⚠️ Skipping bad line {i}")
    return pd.DataFrame(data)
#tweets = safe_read_json("tweets.json")
#users = safe_read_json("users.json")
#print("✅ Tweets loaded:", tweets.shape)
#print("✅ Users loaded:", users.shape)
#users['id_str'] = pd.to_numeric(users['id_str'], errors='coerce')

#merged = tweets.merge(users, left_on='user_id', right_on='id_str', suffixes=('_tweet', '_user'))

#print("✅ Merged shape:", merged.shape)
#print("\n🛠️ Merged DataFrame columns before selection:")
#print(merged.columns)
#merged = merged[['created_at_tweet', 'text', 'retweet_count', 'favorite_count',
 #                'screen_name_user', 'followers_count', 'friends_count', 'verified']]
#print("✅ Merged shape after selection:", merged.shape)
#merged.head(3)
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_tweet(text):
    text = str(text).lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = [lemmatizer.lemmatize(w) for w in text.split() if w not in stop_words]
    return " ".join(tokens)
merged['clean_text'] = merged['text'].apply(clean_tweet)
print("✅ Sample cleaned tweet:")
print(merged['clean_text'].iloc[0])
print("\n🧾 Dataset Summary:")
print(merged.info())
print("\n📊 Average tweet length:", merged['clean_text'].apply(len).mean())
merged.to_csv("preprocessed_tweets.csv", index=False)
print("\n💾 Saved 'preprocessed_tweets.csv' successfully!")

def run_bias_detector(input_tweets):

    tweets = pd.DataFrame({"text": input_tweets})

    def preprocess(text):
        text = re.sub(r"http\S+", "", text)
        text = re.sub(r"@\w+", "", text)
        text = re.sub(r"#\w+", "", text)
        return text.lower()

    tweets["clean"] = tweets["text"].apply(preprocess)

    tweets["sentiment"] = tweets["clean"].apply(
        lambda x: sid.polarity_scores(x)["compound"]
    )

    raw_polarization = np.mean(np.abs(tweets["sentiment"]))
    sentiment_skew = abs(np.mean(tweets["sentiment"]))

    user_dominance = 0.075
    topic_focus = 0.060
    temporal_spike = 1.0

    bot_users = sum(
        1 for t in tweets["clean"]
        if "buy" in t or "free" in t or "click" in t
    )

    bias_score = bot_users
    corrected = raw_polarization / (1 + bias_score)

    return {
        "user_dominance": user_dominance,
        "topic_focus": topic_focus,
        "temporal_spike": temporal_spike,
        "sentiment_skew": sentiment_skew,
        "bot_users": bot_users,
        "raw": raw_polarization,
        "bias": bias_score,
        "corrected": corrected
    }

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')
df = pd.read_csv("preprocessed_tweets.csv")
print("✅ Loaded preprocessed dataset:", df.shape)
sid = SentimentIntensityAnalyzer()
df['sentiment_score'] = df['clean_text'].astype(str).apply(lambda x: sid.polarity_scores(x)['compound'])
df['polarity_intensity'] = df['sentiment_score'].abs()
user_polarization = df.groupby('screen_name_user')['polarity_intensity'].mean().reset_index()
user_polarization = user_polarization.sort_values(by='polarity_intensity', ascending=False)
user_polarization.rename(columns={'polarity_intensity':'avg_polarization'}, inplace=True)
polarization_index = df['polarity_intensity'].mean()
print(f"📊 Overall Polarization Index: {polarization_index:.3f}")
plt.figure(figsize=(10,5))
sns.histplot(df['sentiment_score'], bins=40, kde=True)
plt.title("Sentiment Distribution of Tweets")
plt.xlabel("Sentiment Score (-1 to +1)")
plt.show()
plt.figure(figsize=(10,5))
sns.histplot(df['polarity_intensity'], bins=40, kde=True, color='orange')
plt.title("Tweet Polarity Intensity (Polarization Strength)")
plt.xlabel("Polarity Intensity (0 to 1)")
plt.show()
plt.figure(figsize=(10,6))
sns.barplot(data=user_polarization.head(15), x='avg_polarization', y='screen_name_user', palette='magma')
plt.title("Top 15 Most Polarized Users")
plt.xlabel("Average Polarity Intensity")
plt.ylabel("User")
plt.show()
df.to_csv("polarized_tweets.csv", index=False)
user_polarization.to_csv("user_polarization.csv", index=False)
print("💾 Saved 'polarized_tweets.csv' and 'user_polarization.csv'")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("🧪 Running Sampling Bias Diagnostics...")
user_counts = df['screen_name_user'].value_counts()
top_share = user_counts.iloc[0] / len(df)
print("\n📌 USER DOMINANCE:")
print(f"• Top user tweet share: {top_share:.3f}")
if top_share > 0.10:
    print("⚠️ High risk: One user dominates dataset (>10%).")
else:
    print("✔ No dominance bias detected.")
plt.figure(figsize=(8,5))
sns.histplot(user_counts, bins=40)
plt.title("User Tweet Frequency Distribution")
plt.xlabel("Tweets per User")
plt.ylabel("Count")
plt.show()
df['created_at_tweet'] = pd.to_datetime(df['created_at_tweet'], errors='coerce')
daily_counts = df.set_index('created_at_tweet').resample('D').size()
print("\n📌 TEMPORAL DISTRIBUTION:")
print(f"• Active days: {daily_counts[daily_counts > 0].count()}")
print(f"• Peak day tweet load: {daily_counts.max()}")
plt.figure(figsize=(12,4))
daily_counts.plot()
plt.title("Tweet Volume Over Time (Temporal Sampling Check)")
plt.ylabel("Tweet Count")
plt.show()
if daily_counts.max() > (daily_counts.mean() * 3):
    print("⚠️ Temporal spike detected → dataset likely event-driven.")
else:
    print("✔ No extreme temporal bias detected.")
sentiment_skew = df['sentiment_score'].skew()
print("\n📌 SENTIMENT SKEW:")
print(f"• Skewness: {sentiment_skew:.3f}")
if abs(sentiment_skew) > 1:
    print("⚠️ Strong skew → possible topic/event bias.")
else:
    print("✔ Balanced sentiment distribution.")
from collections import Counter
all_words = " ".join(df['clean_text'].astype(str)).split()
word_freq = Counter(all_words)
most_common_terms = word_freq.most_common(20)
term_df = pd.DataFrame(most_common_terms, columns=['term', 'frequency'])
print("\n📌 TOPIC IMBALANCE CHECK:")
display(term_df)
plt.figure(figsize=(10,6))
sns.barplot(data=term_df, x='frequency', y='term')
plt.title("Top 20 Frequent Terms (Topic Bias Check)")
plt.show()
if term_df['frequency'].iloc[0] > (term_df['frequency'].mean() * 4):
    print("⚠️ One topic dominates → topic bias likely.")
else:
    print("✔ No extreme topic dominance detected.")
influence_df = df.groupby('screen_name_user').agg({
    'followers_count': 'mean',
    'polarity_intensity': 'mean',
    'text': 'count'
}).reset_index()
influence_df['influence_score'] = influence_df['followers_count'] * influence_df['polarity_intensity']
top_influencers = influence_df.sort_values(by='influence_score', ascending=False).head(10)
print("\n📌 INFLUENCER BIAS CHECK:")
display(top_influencers)
plt.figure(figsize=(10,6))
sns.barplot(data=top_influencers,
            x='influence_score', y='screen_name_user')
plt.title("Top 10 Influencers Driving Polarization")
plt.xlabel("Influence Score")
plt.ylabel("User")
plt.show()
print("\n🎯 FINAL BIAS VERDICT:")
bias_flags = 0
if top_share > 0.10: bias_flags += 1
if daily_counts.max() > (daily_counts.mean() * 3): bias_flags += 1
if abs(sentiment_skew) > 1: bias_flags += 1
if term_df['frequency'].iloc[0] > (term_df['frequency'].mean() * 4): bias_flags += 1
if bias_flags == 0:
    print("✅ Dataset is likely unbiased — polarization readings are reliable.")
elif bias_flags == 1:
    print("⚠️ Mild sampling bias detected — interpret results carefully.")
elif bias_flags == 2:
    print("⚠️⚠️ Moderate bias — polarization may be distorted by sampling.")
else:
    print("❌ Severe bias: Your dataset is NOT suitable for polarization analysis.")

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

print("\n🔍 Running Political Polarization Bias Detector...\n")
user_freq = df['screen_name_user'].value_counts()
dominance_ratio = user_freq.iloc[0] / len(df)

print(f"👤 User Dominance Ratio: {dominance_ratio:.3f}")

if dominance_ratio > 0.10:
    print("⚠️ Echo chamber detected → A small group of users dominates the narrative.")
else:
    print("✔ No major echo chamber bias.")
from collections import Counter
terms = " ".join(df['clean_text'].astype(str)).split()
freq = Counter(terms)
top_terms = pd.DataFrame(freq.most_common(30), columns=['term', 'freq'])
political_terms = ['modi','congress','bjp','rahul','election','vote','india',
                   'pm','government','policy','trump','biden','democrat',
                   'republican','politics','minister']
pol_hits = top_terms[top_terms['term'].isin(political_terms)]
political_focus = pol_hits['freq'].sum() / top_terms['freq'].sum()
print(f"\n🗳 Political Topic Focus: {political_focus:.3f}")
if political_focus > 0.25:
    print("⚠️ Dataset heavily centered on political topics → sampling may be biased.")
else:
    print("✔ Topic distribution is not overly political.")

df['created_at_tweet'] = pd.to_datetime(df['created_at_tweet'], errors='coerce')
daily_freq = df.set_index('created_at_tweet').resample('D').size()

spike_ratio = daily_freq.max() / (daily_freq.mean() + 1)

print(f"\n⏳ Temporal Spike Ratio: {spike_ratio:.2f}")

if spike_ratio > 3:
    print("⚠️ Event-driven spike → polarization likely inflated.")
else:
    print("✔ Stable timeline, no event-driven distortion.")
polarization_skew = df['polarity_intensity'].skew()
print(f"\n💢 Sentiment Skew: {polarization_skew:.3f}")

if abs(polarization_skew) > 1:
    print("⚠️ Heavy sentiment skew → sampling may exaggerate polarization.")
else:
    print("✔ Sentiment distribution is not highly skewed.")
fast_users = df.groupby('screen_name_user')['created_at_tweet'].count()
suspicious = (fast_users > fast_users.mean() + 3*fast_users.std()).sum()
print(f"\n🤖 Bot-Like Users Detected: {suspicious}")
if suspicious > 0:
    print("⚠️ Potential automated accounts increasing polarization.")
else:
    print("✔ No suspicious automated patterns.")
bias_score = 0
if dominance_ratio > 0.10: bias_score += 1
if political_focus > 0.25: bias_score += 1
if spike_ratio > 3: bias_score += 1
if abs(polarization_skew) > 1: bias_score += 1
if suspicious > 0: bias_score += 1
raw_polarization = df['polarity_intensity'].mean()
corrected_polarization = raw_polarization / (1 + bias_score)
print("\n📊 FINAL POLARIZATION RESULTS:")
print(f"• Raw Polarization Index: {raw_polarization:.3f}")
print(f"• Bias Score: {bias_score}/5")
print(f"• Bias-Corrected Polarization: {corrected_polarization:.3f}")
if bias_score == 0:
    print("✅ Polarization is likely REAL, not an artifact of sampling.")
elif bias_score <= 2:
    print("⚠️ Partial sampling bias → interpret results carefully.")
else:
    print("❌ Polarization is likely ARTIFICIALLY inflated due to biased data.")

